#!/bin/bash
### set the number of nodes
### set the number of PEs per node
#PBS -l nodes=1:ppn=8:xe
### set the wallclock time
#PBS -l walltime=00:05:00
### set the job name
#PBS -N graphNC
### set queue
#PBS -q debug
### set the job stdout and stderr
#PBS -e $PBS_JOBID.err
#PBS -o $PBS_JOBID.out
### set email notification
##PBS -m torres
##PBS -M walter.torres@duke.edu

module load bwpy
aprun -b -n 1 -- bwpy-environ -- graphNC.py

