name: viz
channels:
  - conda-forge
  - intel
  - defaults
dependencies:
  - xarray
  - netcdf4
  - dask
  - hvplot
  - datashader
#  - python=3.7
  - bokeh
  - cmocean
  - geoviews
  - cartopy
  - holoviews
  - xgcm
  - selenium
  - phantomjs
  - seaborn
prefix:

