#!/bin/bash

# These are the PBS Directives
#PBS -N suntans
#PBS -A uamp0001
#PBS -q main 
#PBS -l walltime=00:30:00
#PBS -l select=1:ncpus=20:mpiprocs=20

# Environment Management
module load ncarenv/24.12
module load intel-oneapi/2024.2.1
module load cray-mpich/8.1.29
#module load netcdf/4.9.2

export suntansproj="$WORK/idealized_siw/suntans-gvc-oblique-iw/examples/T_M1"
#export suntansproj="$WORK/idealized_siw/suntans-gvc-oblique-iw/examples/T_M2_H100"
#echo "$suntansproj"

cd $suntansproj
echo "$suntansproj"

# remove old output data and clean run files
make clean
make -C ../../main clean
mkdir -p data
cp -r ./rundata/* ./data
make data

echo "${suntansproj}/data"

# Scripting
mpiexec -np 20 ../../main/sun -g --datadir=${suntansproj}/data
mpiexec -np 20 ../../main/sun -s -vv --datadir=${suntansproj}/data

cd ~/hpc-tools/derecho
